#!/usr/bin/env python3

import unittest

from pgmpy.base import CoreGraph


class TestCoreGraph(unittest.TestCase):
    def setUp(self):
        self.graph = CoreGraph()

    def test_init_empty(self):
        """Test the initialization of an empty `CoreGraph`"""
        assert len(self.graph.nodes) == 0
        assert len(self.graph.edges) == 0
        assert self.graph.exposures == set()
        assert self.graph.outcomes == set()
        assert self.graph.latents == set()
        assert self.graph.get_role_dict() == {}

    def test_init_with_values(self):
        """Test the initialization of a `CoreGraph` with values"""
        # Task1: Test the initialization of a `CoreGraph` with nodes.
        # ebunch = ...
        # graph1 = CoreGraph()

        assert len(self.graph1.nodes) == ...
        assert len(self.graph1.edges) == ...
        assert self.graph1.exposures == ...
        assert self.graph1.outcomes == ...
        assert self.graph1.latents == ...
        assert self.graph1.get_role_dict() == ...

        # Task2: Test the initialization of a `CoreGraph` with edges.
        # edges = ...
        # graph2 = CoreGraph()

        assert len(self.graph2.nodes) == ...
        assert len(self.graph2.edges) == ...
        assert self.graph2.exposures == ...
        assert self.graph2.outcomes == ...
        assert self.graph2.latents == ...
        assert self.graph2.get_role_dict() == ...

        # Task3: Test the initialization of a `CoreGraph` with exposures.
        # exposures = ...
        # graph3 = CoreGraph()

        assert len(self.graph3.nodes) == ...
        assert len(self.graph3.edges) == ...
        assert self.graph3.exposures == ...
        assert self.graph3.outcomes == ...
        assert self.graph3.latents == ...
        assert self.graph3.get_role_dict() == ...

        # Task4: Test the initialization of a `CoreGraph` with outcomes.
        # outcomes = ...
        # graph4 = CoreGraph()

        assert len(self.graph4.nodes) == ...
        assert len(self.graph4.edges) == ...
        assert self.graph4.exposures == ...
        assert self.graph4.outcomes == ...
        assert self.graph4.latents == ...
        assert self.graph4.get_role_dict() == ...

        # Task5: Test the initialization of a `CoreGraph` with latents.
        # latents = ...
        # graph5 = CoreGraph()

        assert len(self.graph5.nodes) == ...
        assert len(self.graph5.edges) == ...
        assert self.graph5.exposures == ...
        assert self.graph5.outcomes == ...
        assert self.graph5.latents == ...
        assert self.graph5.get_role_dict() == ...

        # Task6: Test the initialization of a `CoreGraph` with roles.
        # roles = ...
        # graph6 = CoreGraph()

        assert len(self.graph6.nodes) == ...
        assert len(self.graph6.edges) == ...
        assert self.graph6.exposures == ...
        assert self.graph6.outcomes == ...
        assert self.graph6.latents == ...
        assert self.graph6.get_role_dict() == ...

        # Task7: Test the initialization of a `CoreGraph` with values.
        # graph7 = CoreGraph()

        assert len(self.graph7.nodes) == ...
        assert len(self.graph7.edges) == ...
        assert self.graph7.exposures == ...
        assert self.graph7.outcomes == ...
        assert self.graph7.latents == ...
        assert self.graph7.get_role_dict() == ...

    def test_is_directed(self):
        assert self.graph.is_directed() == False

    def test_is_multigraph(self):
        assert self.graph.is_multigraph() == True

    def test_add_edge(self):
        """Test the `add_edge` method of the `CoreGraph` class."""
        # Task1: Test adding the direct edge of a `CoreGraph`.
        ...

        # Task2: Test adding the undirect edge of a `CoreGraph`.
        ...

        # Task3: Test adding the bidirect edge of a `CoreGraph`.
        ...

        # Task4: Test adding the unknown edge of a `CoreGraph`.
        ...

        # Task5: Test adding multiedges of a `CoreGraph`.
        ...

        # Task6: Test failing add edge of a `CoreGraph`.
        ...

    def test_add_edges_from(self):
        """Test the `add_edges_from` method of the `CoreGraph` class."""
        # Task1: Test adding the direct edges of a `CoreGraph`.
        ...

        # Task2: Test adding the undirect edges of a `CoreGraph`.
        ...

        # Task3: Test adding the bidirect edges of a `CoreGraph`.
        ...

        # Task4: Test adding the unknown edges of a `CoreGraph`.
        ...

        # Task5: Test adding the various edge of a `CoreGraph`.
        ...

        # Task6: Test adding multiedges of a `CoreGraph`.
        ...

        # Task7: Test failing add edges of a `CoreGraph`.
        ...

    def test_remove_edge(self):
        """Test the `remove_edge` method of the `CoreGraph` class."""
        # Task1: Test removing the direct edge of a `CoreGraph`.
        ...

        # Task2: Test removing the undirect edge of a `CoreGraph`.
        ...

        # Task3: Test removing the bidirect edge of a `CoreGraph`.
        ...

        # Task4: Test removing the unknown edge of a `CoreGraph`.
        ...

        # Task5: Test removing multiedges of a `CoreGraph`.
        ...

        # Task6: Test failing remove edge of a `CoreGraph`.
        ...

    def test_remove_edges_from(self):
        """Test the `remove_edges_from` method of the `CoreGraph` class."""
        # Task1: Test removing the direct edges of a `CoreGraph`.
        ...

        # Task2: Test removing the undirect edges of a `CoreGraph`.
        ...

        # Task3: Test removing the bidirect edges of a `CoreGraph`.
        ...

        # Task4: Test removing the unknown edges of a `CoreGraph`.
        ...

        # Task5: Test removing the various edge of a `CoreGraph`.
        ...

        # Task6: Test removing multiedges of a `CoreGraph`.
        ...

        # Task7: Test failing remove edges of a `CoreGraph`.
        ...

    def test_equality(self):
        """Test the `__eq__` method of the `CoreGraph` class."""
        # Task1: Test the `__eq__` method of the empty `CoreGraph` class.
        ...

        # Task2: Test the `__eq__` method of the `CoreGraph` class with values.
        ...

        # Task3: Test faling the `__eq__` method of the `CoreGraph` class.
        ...

    def test_copy(self):
        """Test the `copy` method of the `CoreGraph` class."""
        # Task1: Test the `copy` method of the empty `CoreGraph` class.
        ...

        # Task2: Test the `copy` method of the `CoreGraph` class with values.
        ...

        # Task3: Test faling the `copy` method of the `CoreGraph` class.
        ...
